// COPYRIGHT Dassault Systemes 2025
//===================================================================
//
// PNXSubCurveDlg.h
// The dialog : PNXSubCurveDlg
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   DIALOG
//End CAA2 Wizard Generation Report
//
//  Oct 2025  Creation: Code generated by the CAA wizard  plm
//===================================================================
#ifndef PNXSubCurveDlg_H
#define PNXSubCurveDlg_H

#include "CATDlgDialog.h"
#include "CATDlgInclude.h"

//----------------------------------------------------------------------

/**
 * Describe the purpose of your panel here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 * <p>
 * refer to programming resources of Dialog framework.
 * (consult base class description).
 */
class PNXSubCurveDlg: public CATDlgDialog
{
  // Allows customization/internationalization of command's messages
  // ---------------------------------------------------------------
  DeclareResource( PNXSubCurveDlg, CATDlgDialog )

  public:

  PNXSubCurveDlg();
  virtual ~PNXSubCurveDlg();

  void Build ();


  protected:

  private:


//CAA2 WIZARD WIDGET DECLARATION SECTION
//END CAA2 WIZARD WIDGET DECLARATION SECTION
};

//----------------------------------------------------------------------

#endif
