// COPYRIGHT Dassault Systemes 2025
//===================================================================
//
// PNXSubCurveDlg.h
// The dialog : PNXSubCurveDlg
//
//===================================================================
//
// Usage notes:
//
//===================================================================

//
//  Oct 2025  Creation: Code generated by the CAA wizard  plm
//===================================================================
#ifndef PNXSubCurveDlg_H
#define PNXSubCurveDlg_H

#include "CATDlgDialog.h"
#include "CATDlgInclude.h"

//----------------------------------------------------------------------

/**
 * Describe the purpose of your panel here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 * <p>
 * refer to programming resources of Dialog framework.
 * (consult base class description).
 */
class PNXSubCurveDlg : public CATDlgDialog {
    // Allows customization/internationalization of command's messages
    // ---------------------------------------------------------------
    DeclareResource(PNXSubCurveDlg, CATDlgDialog);

public:
    PNXSubCurveDlg(CATDlgDialog* ipParent);
    virtual ~PNXSubCurveDlg();

    void Build();

protected:
    /**
     * @brief Callback on DiaCANCEL of _PNXSubCurveDlg
     */
    virtual void OnPNXSubCurveDlgDiaCANCELNotification(CATCommand*, CATNotification*,
                                                       CATCommandClientData data);

private:
    // clang-format off
//CAA2 WIZARD WIDGET DECLARATION SECTION
 CATDlgFrame*      _FrameTop;
 CATDlgLabel*      _Label002;
 CATDlgCheckButton*      _CheckButton003;
 CATDlgTabContainer*      _TabContainer004;
 CATDlgTabPage*      _TabPage005;
 CATDlgRadioButton*      _RadioButton006;
 CATDlgRadioButton*      _RadioButton007;
 CATDlgFrame*      _Frame008;
 CATDlgRadioButton*      _RadioButton009;
 CATDlgRadioButton*      _RadioButton010;
 CATDlgMultiList*      _MultiList011;
 CATDlgSelectorList*      _SelectorList012;
//END CAA2 WIZARD WIDGET DECLARATION SECTION
    // clang-format on
};

//----------------------------------------------------------------------

#endif
